#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Modelos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SOFTVET")]
	public partial class MSOFTVETDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertVacuna(Vacuna instance);
    partial void UpdateVacuna(Vacuna instance);
    partial void DeleteVacuna(Vacuna instance);
    #endregion
		
		public MSOFTVETDataContext() : 
				base(global::ProyectoFinal.Properties.Settings.Default.SOFTVETConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MSOFTVETDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MSOFTVETDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MSOFTVETDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MSOFTVETDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Vacuna> Vacuna
		{
			get
			{
				return this.GetTable<Vacuna>();
			}
		}
		
		public System.Data.Linq.Table<V_Desparasitacion> V_Desparasitacion
		{
			get
			{
				return this.GetTable<V_Desparasitacion>();
			}
		}
		
		public System.Data.Linq.Table<V_Empleado> V_Empleado
		{
			get
			{
				return this.GetTable<V_Empleado>();
			}
		}
		
		public System.Data.Linq.Table<V_Paciente> V_Paciente
		{
			get
			{
				return this.GetTable<V_Paciente>();
			}
		}
		
		public System.Data.Linq.Table<V_Paciente_Vacuna> V_Paciente_Vacuna
		{
			get
			{
				return this.GetTable<V_Paciente_Vacuna>();
			}
		}
		
		public System.Data.Linq.Table<V_Recetaciones> V_Recetaciones
		{
			get
			{
				return this.GetTable<V_Recetaciones>();
			}
		}
		
		public System.Data.Linq.Table<V_Usuario> V_Usuario
		{
			get
			{
				return this.GetTable<V_Usuario>();
			}
		}
		
		public System.Data.Linq.Table<V_Vacunacion> V_Vacunacion
		{
			get
			{
				return this.GetTable<V_Vacunacion>();
			}
		}
		
		public System.Data.Linq.Table<V_Vacunas> V_Vacunas
		{
			get
			{
				return this.GetTable<V_Vacunas>();
			}
		}
		
		public System.Data.Linq.Table<V_Citas> V_Citas
		{
			get
			{
				return this.GetTable<V_Citas>();
			}
		}
		
		public System.Data.Linq.Table<V_CargarCitas> V_CargarCitas
		{
			get
			{
				return this.GetTable<V_CargarCitas>();
			}
		}
		
		public System.Data.Linq.Table<V_DETALLE_PACIENTE_VACUNA> V_DETALLE_PACIENTE_VACUNA
		{
			get
			{
				return this.GetTable<V_DETALLE_PACIENTE_VACUNA>();
			}
		}
		
		public System.Data.Linq.Table<V_Cliente> V_Cliente
		{
			get
			{
				return this.GetTable<V_Cliente>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Actualizar_StockVacuna")]
		public int SP_Actualizar_StockVacuna([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Vacuna", DbType="Int")] System.Nullable<int> id_Vacuna, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NroDosisAjuste", DbType="Int")] System.Nullable<int> nroDosisAjuste)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Vacuna, nroDosisAjuste);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Agregar_Desparasitacion")]
		public int SP_Agregar_Desparasitacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cod_paciente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tipo, fecha, cod_paciente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Agregar_Recetacion")]
		public int SP_Agregar_Recetacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cod_paciente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, fecha, cod_paciente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AgregarEmpleado")]
		public int SP_AgregarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string dni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string fechanac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sexo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string fechaing, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string cargo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string horario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(6)")] string sueldo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, apellido, dni, fechanac, sexo, telefono, fechaing, cargo, horario, sueldo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AgregarPaciente")]
		public int SP_AgregarPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string especie, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string raza, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string sexo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string cod_cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, especie, raza, sexo, fecha, cod_cliente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AgregarPaciente_Vacuna")]
		public int SP_AgregarPaciente_Vacuna([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string cod_paciente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string idVacuna, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string nrodosis, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cod_paciente, idVacuna, nrodosis, fecha);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AgregarVacuna")]
		public int SP_AgregarVacuna([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string stock, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_caducidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, stock, fecha_caducidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CancelarCita")]
		public int SP_CancelarCita([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCita", DbType="Int")] System.Nullable<int> idCita)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCita);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Eliminar_Desparasitacion")]
		public int SP_Eliminar_Desparasitacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_disparasitacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_disparasitacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarCita")]
		public int SP_EliminarCita([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Cita", DbType="Int")] System.Nullable<int> iD_Cita)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Cita);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarStockVacuna")]
		public int SP_EliminarStockVacuna([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Vacuna", DbType="Int")] System.Nullable<int> id_Vacuna, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NroDosisAjuste", DbType="Int")] System.Nullable<int> nroDosisAjuste)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Vacuna, nroDosisAjuste);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Modificar_Desparasitacion")]
		public int SP_Modificar_Desparasitacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_disparasitacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cod_paciente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_disparasitacion, tipo, fecha, cod_paciente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Modificar_Vacunacion")]
		public int SP_Modificar_Vacunacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_detalle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cod_paciente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string id_vacuna, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string numdosis, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_detalle, cod_paciente, id_vacuna, numdosis, fecha);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ReducirStockVacuna")]
		public int SP_ReducirStockVacuna([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Vacuna", DbType="Int")] System.Nullable<int> iD_Vacuna, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] System.Nullable<int> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Vacuna, cantidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Eliminar_Vacunacion")]
		public int SP_Eliminar_Vacunacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_detalle)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_detalle);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarCliente")]
		public int SP_EliminarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cod_Cliente", DbType="Int")] System.Nullable<int> cod_Cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cod_Cliente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificarPaciente")]
		public int SP_ModificarPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodPaciente", DbType="Int")] System.Nullable<int> codPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Especie", DbType="VarChar(50)")] string especie, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Raza", DbType="VarChar(50)")] string raza, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sexo", DbType="VarChar(10)")] string sexo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaNacimiento", DbType="Date")] System.Nullable<System.DateTime> fechaNacimiento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codPaciente, nombre, especie, raza, sexo, fechaNacimiento);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarPaciente")]
		public int SP_EliminarPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodPaciente", DbType="Int")] System.Nullable<int> codPaciente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codPaciente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificarEmpleado")]
		public int SP_ModificarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DNI", DbType="VarChar(8)")] string dNI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaNacimiento", DbType="Date")] System.Nullable<System.DateTime> fechaNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Genero", DbType="VarChar(10)")] string genero, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(15)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaInicio", DbType="Date")] System.Nullable<System.DateTime> fechaInicio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cargo", DbType="VarChar(50)")] string cargo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Horario", DbType="VarChar(20)")] string horario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sueldo", DbType="Int")] System.Nullable<int> sueldo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nombre, apellido, dNI, fechaNacimiento, genero, telefono, fechaInicio, cargo, horario, sueldo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarEmpleado")]
		public int SP_EliminarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cod_Empleado", DbType="Int")] System.Nullable<int> cod_Empleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cod_Empleado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AgregarUsuario")]
		public int SP_AgregarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string pass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string cat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string id_Empleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, pass, cat, id_Empleado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Autenticar")]
		public ISingleResult<SP_AutenticarResult> SP_Autenticar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string clave)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, clave);
			return ((ISingleResult<SP_AutenticarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Hvacunacion")]
		public ISingleResult<SP_HvacunacionResult> SP_Hvacunacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codpac)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codpac);
			return ((ISingleResult<SP_HvacunacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Hdesparacitacion")]
		public ISingleResult<SP_HdesparacitacionResult> SP_Hdesparacitacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codpac)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codpac);
			return ((ISingleResult<SP_HdesparacitacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AgregarCita")]
		public int SP_AgregarCita([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Motivo", DbType="VarChar(255)")] string motivo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hora", DbType="VarChar(10)")] string hora, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cod_Cliente", DbType="Int")] System.Nullable<int> cod_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(50)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tamaño", DbType="VarChar(50)")] string tamaño, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cod_Paciente", DbType="Int")] System.Nullable<int> cod_Paciente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), motivo, fecha, hora, cod_Cliente, estado, tamaño, cod_Paciente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EditarCita")]
		public int SP_EditarCita([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Cita", DbType="Int")] System.Nullable<int> iD_Cita, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Motivo", DbType="NVarChar(MAX)")] string motivo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hora", DbType="VarChar(10)")] string hora, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(50)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tamaño", DbType="VarChar(50)")] string tamaño)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Cita, motivo, fecha, hora, estado, tamaño);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Agregar_Vacunacion")]
		public int SP_Agregar_Vacunacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cod_paciente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string id_vacuna, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string numdosis, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cod_paciente, id_vacuna, numdosis, fecha);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_HRecetacion")]
		public ISingleResult<SP_HRecetacionResult> SP_HRecetacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codpac)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codpac);
			return ((ISingleResult<SP_HRecetacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PacientexCliente")]
		public ISingleResult<SP_PacientexClienteResult> SP_PacientexCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string dni)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dni);
			return ((ISingleResult<SP_PacientexClienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AgregarCliente")]
		public int SP_AgregarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string genero, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string dni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string correo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, apellido, telefono, genero, dni, direccion, correo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificarCliente")]
		public int SP_ModificarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cod_Cliente", DbType="Int")] System.Nullable<int> cod_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="NVarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="NVarChar(15)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Genero", DbType="NVarChar(15)")] string genero, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DNI", DbType="NVarChar(8)")] string dNI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="NVarChar(100)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string correo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cod_Cliente, nombre, apellido, telefono, genero, dNI, direccion, correo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BuscarCliente")]
		public ISingleResult<SP_BuscarClienteResult> SP_BuscarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DNI", DbType="VarChar(8)")] string dNI)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dNI);
			return ((ISingleResult<SP_BuscarClienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Agregar_Abast_Vacunas")]
		public int SP_Agregar_Abast_Vacunas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stock, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_cad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, stock, fecha_cad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Eliminar_Abast_Vacunas")]
		public int SP_Eliminar_Abast_Vacunas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_vacuna)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_vacuna);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Modificar_Abast_Vacunas")]
		public int SP_Modificar_Abast_Vacunas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_vacuna, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stock, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_cad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_vacuna, nombre, stock, fecha_cad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_TotalStockVacuna")]
		public ISingleResult<SP_TotalStockVacunaResult> SP_TotalStockVacuna()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_TotalStockVacunaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_HistorialClinico")]
		public ISingleResult<SP_HistorialClinicoResult> SP_HistorialClinico([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<SP_HistorialClinicoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPR_Hvacunacion")]
		public ISingleResult<SPR_HvacunacionResult> SPR_Hvacunacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<SPR_HvacunacionResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vacuna")]
	public partial class Vacuna : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Vacuna;
		
		private string _Nombre_Vacuna;
		
		private int _Stock;
		
		private System.DateTime _FechaCaducidad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VacunaChanging(int value);
    partial void OnID_VacunaChanged();
    partial void OnNombre_VacunaChanging(string value);
    partial void OnNombre_VacunaChanged();
    partial void OnStockChanging(int value);
    partial void OnStockChanged();
    partial void OnFechaCaducidadChanging(System.DateTime value);
    partial void OnFechaCaducidadChanged();
    #endregion
		
		public Vacuna()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Vacuna", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Vacuna
		{
			get
			{
				return this._ID_Vacuna;
			}
			set
			{
				if ((this._ID_Vacuna != value))
				{
					this.OnID_VacunaChanging(value);
					this.SendPropertyChanging();
					this._ID_Vacuna = value;
					this.SendPropertyChanged("ID_Vacuna");
					this.OnID_VacunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Vacuna", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre_Vacuna
		{
			get
			{
				return this._Nombre_Vacuna;
			}
			set
			{
				if ((this._Nombre_Vacuna != value))
				{
					this.OnNombre_VacunaChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Vacuna = value;
					this.SendPropertyChanged("Nombre_Vacuna");
					this.OnNombre_VacunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Int NOT NULL")]
		public int Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this.OnStockChanging(value);
					this.SendPropertyChanging();
					this._Stock = value;
					this.SendPropertyChanged("Stock");
					this.OnStockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCaducidad", DbType="Date NOT NULL")]
		public System.DateTime FechaCaducidad
		{
			get
			{
				return this._FechaCaducidad;
			}
			set
			{
				if ((this._FechaCaducidad != value))
				{
					this.OnFechaCaducidadChanging(value);
					this.SendPropertyChanging();
					this._FechaCaducidad = value;
					this.SendPropertyChanged("FechaCaducidad");
					this.OnFechaCaducidadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Desparasitacion")]
	public partial class V_Desparasitacion
	{
		
		private int _id;
		
		private string _tipo;
		
		private System.DateTime _Fecha;
		
		private int _cod_Paciente;
		
		public V_Desparasitacion()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this._tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_Paciente", DbType="Int NOT NULL")]
		public int cod_Paciente
		{
			get
			{
				return this._cod_Paciente;
			}
			set
			{
				if ((this._cod_Paciente != value))
				{
					this._cod_Paciente = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Empleado")]
	public partial class V_Empleado
	{
		
		private int _Cod_Empleado;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _DNI;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Sexo;
		
		private string _Telefono;
		
		private System.DateTime _Fecha_Ingreso;
		
		private string _Cargo;
		
		private string _Horario;
		
		private int _Sueldo;
		
		public V_Empleado()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Empleado", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Cod_Empleado
		{
			get
			{
				return this._Cod_Empleado;
			}
			set
			{
				if ((this._Cod_Empleado != value))
				{
					this._Cod_Empleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this._DNI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this._Sexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Ingreso", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Ingreso
		{
			get
			{
				return this._Fecha_Ingreso;
			}
			set
			{
				if ((this._Fecha_Ingreso != value))
				{
					this._Fecha_Ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this._Cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horario", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Horario
		{
			get
			{
				return this._Horario;
			}
			set
			{
				if ((this._Horario != value))
				{
					this._Horario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sueldo", DbType="Int NOT NULL")]
		public int Sueldo
		{
			get
			{
				return this._Sueldo;
			}
			set
			{
				if ((this._Sueldo != value))
				{
					this._Sueldo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Paciente")]
	public partial class V_Paciente
	{
		
		private int _Cod_Paciente;
		
		private string _Nombre;
		
		private string _Especie;
		
		private string _Raza;
		
		private string _Sexo;
		
		private System.DateTime _Fecha;
		
		private int _Cod_Cliente;
		
		public V_Paciente()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Paciente", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Cod_Paciente
		{
			get
			{
				return this._Cod_Paciente;
			}
			set
			{
				if ((this._Cod_Paciente != value))
				{
					this._Cod_Paciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especie", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string Especie
		{
			get
			{
				return this._Especie;
			}
			set
			{
				if ((this._Especie != value))
				{
					this._Especie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Raza", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Raza
		{
			get
			{
				return this._Raza;
			}
			set
			{
				if ((this._Raza != value))
				{
					this._Raza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this._Sexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Cliente", DbType="Int NOT NULL")]
		public int Cod_Cliente
		{
			get
			{
				return this._Cod_Cliente;
			}
			set
			{
				if ((this._Cod_Cliente != value))
				{
					this._Cod_Cliente = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Paciente_Vacuna")]
	public partial class V_Paciente_Vacuna
	{
		
		private int _Cod_Paciente;
		
		private int _ID_Vacuna;
		
		private string _NumDosis;
		
		private System.DateTime _Fecha;
		
		public V_Paciente_Vacuna()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Paciente", DbType="Int NOT NULL")]
		public int Cod_Paciente
		{
			get
			{
				return this._Cod_Paciente;
			}
			set
			{
				if ((this._Cod_Paciente != value))
				{
					this._Cod_Paciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Vacuna", DbType="Int NOT NULL")]
		public int ID_Vacuna
		{
			get
			{
				return this._ID_Vacuna;
			}
			set
			{
				if ((this._ID_Vacuna != value))
				{
					this._ID_Vacuna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumDosis", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string NumDosis
		{
			get
			{
				return this._NumDosis;
			}
			set
			{
				if ((this._NumDosis != value))
				{
					this._NumDosis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Recetaciones")]
	public partial class V_Recetaciones
	{
		
		private int _id;
		
		private string _Descripcion_Receta;
		
		private System.DateTime _Fecha_Receta;
		
		private int _cod_paciente;
		
		public V_Recetaciones()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion_Receta", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Descripcion_Receta
		{
			get
			{
				return this._Descripcion_Receta;
			}
			set
			{
				if ((this._Descripcion_Receta != value))
				{
					this._Descripcion_Receta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Receta", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Receta
		{
			get
			{
				return this._Fecha_Receta;
			}
			set
			{
				if ((this._Fecha_Receta != value))
				{
					this._Fecha_Receta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_paciente", DbType="Int NOT NULL")]
		public int cod_paciente
		{
			get
			{
				return this._cod_paciente;
			}
			set
			{
				if ((this._cod_paciente != value))
				{
					this._cod_paciente = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Usuario")]
	public partial class V_Usuario
	{
		
		private int _Id_Usuario;
		
		private string _Username;
		
		private string _Contraseña;
		
		private int _Cod_Empleado;
		
		public V_Usuario()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this._Id_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Empleado", DbType="Int NOT NULL")]
		public int Cod_Empleado
		{
			get
			{
				return this._Cod_Empleado;
			}
			set
			{
				if ((this._Cod_Empleado != value))
				{
					this._Cod_Empleado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Vacunacion")]
	public partial class V_Vacunacion
	{
		
		private int _Id_Detalle;
		
		private int _Cod_Paciente;
		
		private int _ID_Vacuna;
		
		private string _NumDosis;
		
		private System.DateTime _Fecha;
		
		public V_Vacunacion()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Detalle", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id_Detalle
		{
			get
			{
				return this._Id_Detalle;
			}
			set
			{
				if ((this._Id_Detalle != value))
				{
					this._Id_Detalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Paciente", DbType="Int NOT NULL")]
		public int Cod_Paciente
		{
			get
			{
				return this._Cod_Paciente;
			}
			set
			{
				if ((this._Cod_Paciente != value))
				{
					this._Cod_Paciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Vacuna", DbType="Int NOT NULL")]
		public int ID_Vacuna
		{
			get
			{
				return this._ID_Vacuna;
			}
			set
			{
				if ((this._ID_Vacuna != value))
				{
					this._ID_Vacuna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumDosis", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string NumDosis
		{
			get
			{
				return this._NumDosis;
			}
			set
			{
				if ((this._NumDosis != value))
				{
					this._NumDosis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Vacunas")]
	public partial class V_Vacunas
	{
		
		private int _ID_Vacuna;
		
		private string _Nombre_Vacuna;
		
		private int _Stock;
		
		private System.DateTime _FechaCaducidad;
		
		public V_Vacunas()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Vacuna", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID_Vacuna
		{
			get
			{
				return this._ID_Vacuna;
			}
			set
			{
				if ((this._ID_Vacuna != value))
				{
					this._ID_Vacuna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Vacuna", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre_Vacuna
		{
			get
			{
				return this._Nombre_Vacuna;
			}
			set
			{
				if ((this._Nombre_Vacuna != value))
				{
					this._Nombre_Vacuna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Int NOT NULL")]
		public int Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this._Stock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCaducidad", DbType="Date NOT NULL")]
		public System.DateTime FechaCaducidad
		{
			get
			{
				return this._FechaCaducidad;
			}
			set
			{
				if ((this._FechaCaducidad != value))
				{
					this._FechaCaducidad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Citas")]
	public partial class V_Citas
	{
		
		private int _ID_Cita;
		
		private string _Motivo;
		
		private System.DateTime _Fecha;
		
		private string _Hora;
		
		private string _Estado;
		
		private int _Cod_Cliente;
		
		public V_Citas()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Cita", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID_Cita
		{
			get
			{
				return this._ID_Cita;
			}
			set
			{
				if ((this._ID_Cita != value))
				{
					this._ID_Cita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motivo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Motivo
		{
			get
			{
				return this._Motivo;
			}
			set
			{
				if ((this._Motivo != value))
				{
					this._Motivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora", DbType="VarChar(10)")]
		public string Hora
		{
			get
			{
				return this._Hora;
			}
			set
			{
				if ((this._Hora != value))
				{
					this._Hora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Cliente", DbType="Int NOT NULL")]
		public int Cod_Cliente
		{
			get
			{
				return this._Cod_Cliente;
			}
			set
			{
				if ((this._Cod_Cliente != value))
				{
					this._Cod_Cliente = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_CargarCitas")]
	public partial class V_CargarCitas
	{
		
		private int _ID_Cita;
		
		private string _Motivo;
		
		private System.DateTime _Fecha;
		
		private string _Hora;
		
		private string _Estado;
		
		private string _Tamaño;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Paciente;
		
		private int _Cod_Cliente;
		
		public V_CargarCitas()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Cita", DbType="Int NOT NULL")]
		public int ID_Cita
		{
			get
			{
				return this._ID_Cita;
			}
			set
			{
				if ((this._ID_Cita != value))
				{
					this._ID_Cita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motivo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Motivo
		{
			get
			{
				return this._Motivo;
			}
			set
			{
				if ((this._Motivo != value))
				{
					this._Motivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora", DbType="VarChar(10)")]
		public string Hora
		{
			get
			{
				return this._Hora;
			}
			set
			{
				if ((this._Hora != value))
				{
					this._Hora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tamaño", DbType="VarChar(50)")]
		public string Tamaño
		{
			get
			{
				return this._Tamaño;
			}
			set
			{
				if ((this._Tamaño != value))
				{
					this._Tamaño = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paciente", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Paciente
		{
			get
			{
				return this._Paciente;
			}
			set
			{
				if ((this._Paciente != value))
				{
					this._Paciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Cliente", DbType="Int NOT NULL")]
		public int Cod_Cliente
		{
			get
			{
				return this._Cod_Cliente;
			}
			set
			{
				if ((this._Cod_Cliente != value))
				{
					this._Cod_Cliente = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_DETALLE_PACIENTE_VACUNA")]
	public partial class V_DETALLE_PACIENTE_VACUNA
	{
		
		private int _ID;
		
		private string _Nombre_Paciente;
		
		private string _Nombre_Vacuna;
		
		private string _Nro_Dosis;
		
		private System.DateTime _Fecha_Hora;
		
		public V_DETALLE_PACIENTE_VACUNA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Paciente", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre_Paciente
		{
			get
			{
				return this._Nombre_Paciente;
			}
			set
			{
				if ((this._Nombre_Paciente != value))
				{
					this._Nombre_Paciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Vacuna", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre_Vacuna
		{
			get
			{
				return this._Nombre_Vacuna;
			}
			set
			{
				if ((this._Nombre_Vacuna != value))
				{
					this._Nombre_Vacuna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nro_Dosis", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string Nro_Dosis
		{
			get
			{
				return this._Nro_Dosis;
			}
			set
			{
				if ((this._Nro_Dosis != value))
				{
					this._Nro_Dosis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha-Hora]", Storage="_Fecha_Hora", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Hora
		{
			get
			{
				return this._Fecha_Hora;
			}
			set
			{
				if ((this._Fecha_Hora != value))
				{
					this._Fecha_Hora = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Cliente")]
	public partial class V_Cliente
	{
		
		private int _Cod_Cliente;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Telefono;
		
		private string _Género;
		
		private string _DNI;
		
		private string _Dirección;
		
		private string _Correo;
		
		public V_Cliente()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Cliente", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Cod_Cliente
		{
			get
			{
				return this._Cod_Cliente;
			}
			set
			{
				if ((this._Cod_Cliente != value))
				{
					this._Cod_Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Género", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Género
		{
			get
			{
				return this._Género;
			}
			set
			{
				if ((this._Género != value))
				{
					this._Género = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this._DNI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dirección", DbType="VarChar(50)")]
		public string Dirección
		{
			get
			{
				return this._Dirección;
			}
			set
			{
				if ((this._Dirección != value))
				{
					this._Dirección = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
	}
	
	public partial class SP_AutenticarResult
	{
		
		private int _ID_USUARIO;
		
		private string _APELLIDO;
		
		private string _NOMBRE;
		
		private string _Username;
		
		private string _Categoria;
		
		public SP_AutenticarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string APELLIDO
		{
			get
			{
				return this._APELLIDO;
			}
			set
			{
				if ((this._APELLIDO != value))
				{
					this._APELLIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
	}
	
	public partial class SP_HvacunacionResult
	{
		
		private string _Nombre_Vacuna;
		
		private string _Numero_Dosis;
		
		private System.DateTime _Fecha;
		
		public SP_HvacunacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nombre Vacuna]", Storage="_Nombre_Vacuna", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre_Vacuna
		{
			get
			{
				return this._Nombre_Vacuna;
			}
			set
			{
				if ((this._Nombre_Vacuna != value))
				{
					this._Nombre_Vacuna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Numero Dosis]", Storage="_Numero_Dosis", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string Numero_Dosis
		{
			get
			{
				return this._Numero_Dosis;
			}
			set
			{
				if ((this._Numero_Dosis != value))
				{
					this._Numero_Dosis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	public partial class SP_HdesparacitacionResult
	{
		
		private string _Desparasitante;
		
		private System.DateTime _Fecha_Aplicada;
		
		public SP_HdesparacitacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Desparasitante", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Desparasitante
		{
			get
			{
				return this._Desparasitante;
			}
			set
			{
				if ((this._Desparasitante != value))
				{
					this._Desparasitante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Aplicada", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Aplicada
		{
			get
			{
				return this._Fecha_Aplicada;
			}
			set
			{
				if ((this._Fecha_Aplicada != value))
				{
					this._Fecha_Aplicada = value;
				}
			}
		}
	}
	
	public partial class SP_HRecetacionResult
	{
		
		private string _Descripción;
		
		private System.DateTime _Fecha_Recetada;
		
		public SP_HRecetacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this._Descripción = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Recetada", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Recetada
		{
			get
			{
				return this._Fecha_Recetada;
			}
			set
			{
				if ((this._Fecha_Recetada != value))
				{
					this._Fecha_Recetada = value;
				}
			}
		}
	}
	
	public partial class SP_PacientexClienteResult
	{
		
		private int _Cod_Paciente;
		
		private string _Nombre;
		
		private string _Especie;
		
		private string _Raza;
		
		private string _Sexo;
		
		private System.DateTime _Fecha;
		
		public SP_PacientexClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Paciente", DbType="Int NOT NULL")]
		public int Cod_Paciente
		{
			get
			{
				return this._Cod_Paciente;
			}
			set
			{
				if ((this._Cod_Paciente != value))
				{
					this._Cod_Paciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especie", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Especie
		{
			get
			{
				return this._Especie;
			}
			set
			{
				if ((this._Especie != value))
				{
					this._Especie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Raza", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Raza
		{
			get
			{
				return this._Raza;
			}
			set
			{
				if ((this._Raza != value))
				{
					this._Raza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this._Sexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	public partial class SP_BuscarClienteResult
	{
		
		private int _Cod_Cliente;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Telefono;
		
		private string _Genero;
		
		private string _DNI;
		
		private string _Direccion;
		
		private string _Correo;
		
		public SP_BuscarClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Cliente", DbType="Int NOT NULL")]
		public int Cod_Cliente
		{
			get
			{
				return this._Cod_Cliente;
			}
			set
			{
				if ((this._Cod_Cliente != value))
				{
					this._Cod_Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Genero
		{
			get
			{
				return this._Genero;
			}
			set
			{
				if ((this._Genero != value))
				{
					this._Genero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this._DNI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
	}
	
	public partial class SP_TotalStockVacunaResult
	{
		
		private System.Nullable<int> _ID_Vacuna;
		
		private string _Nombre_Vacuna;
		
		private System.Nullable<int> _TotalStock;
		
		public SP_TotalStockVacunaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Vacuna", DbType="Int")]
		public System.Nullable<int> ID_Vacuna
		{
			get
			{
				return this._ID_Vacuna;
			}
			set
			{
				if ((this._ID_Vacuna != value))
				{
					this._ID_Vacuna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Vacuna", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre_Vacuna
		{
			get
			{
				return this._Nombre_Vacuna;
			}
			set
			{
				if ((this._Nombre_Vacuna != value))
				{
					this._Nombre_Vacuna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalStock", DbType="Int")]
		public System.Nullable<int> TotalStock
		{
			get
			{
				return this._TotalStock;
			}
			set
			{
				if ((this._TotalStock != value))
				{
					this._TotalStock = value;
				}
			}
		}
	}
	
	public partial class SP_HistorialClinicoResult
	{
		
		private string _Nombre;
		
		private string _Nombre1;
		
		private string _Especie;
		
		private string _Raza;
		
		private string _Sexo;
		
		private System.DateTime _Fecha;
		
		public SP_HistorialClinicoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre1", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre1
		{
			get
			{
				return this._Nombre1;
			}
			set
			{
				if ((this._Nombre1 != value))
				{
					this._Nombre1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especie", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Especie
		{
			get
			{
				return this._Especie;
			}
			set
			{
				if ((this._Especie != value))
				{
					this._Especie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Raza", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Raza
		{
			get
			{
				return this._Raza;
			}
			set
			{
				if ((this._Raza != value))
				{
					this._Raza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this._Sexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	public partial class SPR_HvacunacionResult
	{
		
		private string _Nombre_Vacuna;
		
		private string _Numdosis;
		
		private System.DateTime _fecha;
		
		public SPR_HvacunacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Vacuna", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre_Vacuna
		{
			get
			{
				return this._Nombre_Vacuna;
			}
			set
			{
				if ((this._Nombre_Vacuna != value))
				{
					this._Nombre_Vacuna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numdosis", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string Numdosis
		{
			get
			{
				return this._Numdosis;
			}
			set
			{
				if ((this._Numdosis != value))
				{
					this._Numdosis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
